import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AMIR KHAN
 */
import java.lang.Thread;

public class Cabs extends javax.swing.JFrame implements Runnable {

        /**
         * Creates new form Cabs
         */
        // public static Cabs instance;
        public BookingManager bmgr;
        public DisplayCustomer dcobj;
        int flag = 1;
        public int temp_flag = 1;

        public Cabs(DisplayCustomer dcobj) {
                temp_flag = 0;
                this.dcobj = dcobj;
                this.bmgr = BookingManager.getInstanceOfBookingManager();
                initComponents();
                Thread thread = new Thread(this);
                thread.start();

        }

        // public static Cabs getInstanceOfCabs(Customer cobj, Booking bkg) {
        // if (instance == null)
        // instance = new Cabs(cobj, bkg);
        // return instance;
        // }

        public void check() {
                while (true) {
                        bmgr.isCalledOnce();
                        Booking bkg = bmgr.getBooking(dcobj.getBookingObject().getBookingID());
                        if (bmgr.searchBooking(dcobj.getBookingObject().getBookingID()) && bkg.getStatus() == 1) {
                                // Details detailsobj = Details.getInstanceOfDetails(bkg);
                                dcobj.setBookingObject(bkg);

                                this.setVisible(false);
                                dcobj.getDetailsObject().setVisible(true);

                                // detailsobj.setVisible(true);
                                break;
                        }
                        if (flag == 0) {
                                this.setVisible(false);
                                dcobj.getSearchCabObject().setVisible(true);
                                break;
                        }
                }
        }

        public void run() {
                check();

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jPanel3 = new javax.swing.JPanel();
                jButton1 = new javax.swing.JButton();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel2.setBackground(new java.awt.Color(204, 0, 51));

                jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                jLabel2.setText("CabX");

                jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText("User Name");

                jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(255, 255, 255));
                jLabel3.setText("Profile");
                jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabel3MouseClicked(evt);
                        }
                });

                jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(255, 255, 255));
                jLabel4.setText("Logout");
                jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabel4MouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(jPanel2Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(287, 287, 287).addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel3).addGap(78, 78, 78).addComponent(jLabel4)
                                                .addGap(24, 24, 24)));
                jPanel2Layout.setVerticalGroup(jPanel2Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
                                                .createSequentialGroup().addContainerGap(61, Short.MAX_VALUE)
                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel2).addComponent(jLabel1)
                                                                .addComponent(jLabel3).addComponent(jLabel4))
                                                .addContainerGap()));

                jPanel3.setBackground(new java.awt.Color(255, 255, 255));

                jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jButton1.setForeground(new java.awt.Color(153, 0, 0));
                jButton1.setText("Cancel Booking");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(153, 0, 51));
                jLabel5.setText("Your Booking is successful");

                jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel6.setForeground(new java.awt.Color(153, 0, 51));
                jLabel6.setText("We will let you know as soon as driver accepts the booking");

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(jPanel3Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup().addContainerGap(150, Short.MAX_VALUE)
                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                jPanel3Layout.createSequentialGroup()
                                                                                                .addComponent(jLabel5)
                                                                                                .addGap(319, 319, 319))
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                jPanel3Layout.createSequentialGroup()
                                                                                                .addComponent(jLabel6)
                                                                                                .addGap(102, 102, 102))
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                jPanel3Layout.createSequentialGroup()
                                                                                                .addComponent(jButton1)
                                                                                                .addGap(392, 392,
                                                                                                                392)))));
                jPanel3Layout.setVerticalGroup(jPanel3Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout
                                                .createSequentialGroup().addGap(51, 51, 51).addComponent(jLabel5)
                                                .addGap(49, 49, 49).addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76,
                                                                Short.MAX_VALUE)
                                                .addComponent(jButton1).addGap(36, 36, 36)));

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                jPanel1Layout.setVerticalGroup(jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }// </editor-fold>

        private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {
                this.setVisible(false);
                // Profile.getProfileObject(1, cobj).setVisible(true);
                dcobj.getProfileObject().setVisible(true);
                // TODO add your handling code here:
        }

        private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {
                this.setVisible(false);
                // loginobj.setVisible(true);
                dcobj.getLoginObject().setVisible(true);
                // TODO add your handling code here:
        }

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
                BookingManager bmgr = BookingManager.getInstanceOfBookingManager();
                // System.out.println(dcobj.getBookingObject().getBookingID());
                // dcobj.getBookingObject().setBookingID(bmgr.getMaxBookingID() + 1);
                bmgr.isCalledOnce();
                int cflag = 0;

                while (true) {
                        try {
                                if (bmgr.removeBooking(dcobj.getBookingObject().getBookingID())) {
                                        JOptionPane.showMessageDialog(this, "Booking cancelled successfully");
                                        this.setVisible(false);
                                        // instance = null;
                                        flag = 0;
                                        temp_flag = 1;
                                        // searchCabUIobj.setVisible(true);
                                        dcobj.getSearchCabObject().setVisible(true);
                                        cflag = 1;
                                        break;
                                }
                        } catch (IndexOutOfBoundsException e) {

                                // TODO: handle exception
                        }
                        if (cflag == 1)
                                break;
                }

                // TODO add your handling code here:
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel. For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */

                // </editor-fold>

                /* Create and display the form */
                // java.awt.EventQueue.invokeLater(new Runnable() {
                // public void run() {
                // new Cabs().setVisible(true);
                // }
                // });
        }

        // Variables declaration - do not modify
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        // End of variables declaration
}
