/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AMIR KHAN
 */

import java.math.*;

import javax.swing.JOptionPane;

import java.lang.Thread;

public class Details extends javax.swing.JFrame implements Runnable {

        public DisplayCustomer dcobj;
        public DisplayDriver ddobj;
        // public Booking bobj;
        public Object obj;
        public int flag = 1;

        /**
         * Creates new form Details
         */
        public Details(Object obj) {
                this.obj = obj;
                flag = 0;

                dcobj = (DisplayCustomer) obj;
                int fare = Math.abs(Integer.parseInt(dcobj.getBookingObject().getDropLocation())
                                - Integer.parseInt(dcobj.getBookingObject().getPickupLocation())) + 30;
                dcobj.getBookingObject().setFare(fare);

                initComponents();
                Thread thread = new Thread(this);
                thread.start();

        }

        public void check() {
                while (true) {
                        BookingManager bmgr = BookingManager.getInstanceOfBookingManager();
                        bmgr.isCalledOnce();
                        Booking bkg = bmgr.getBooking(dcobj.getBookingObject().getBookingID());
                        if (bmgr.searchBooking(dcobj.getBookingObject().getBookingID()) && bkg.getStatus() == 0) {
                                // Details detailsobj = Details.getInstanceOfDetails(bkg);
                                JOptionPane.showMessageDialog(this,
                                                "Driver has cancelled the booking wait for another driver to accept");
                                // dcobj.setBookingObject(bkg);

                                this.setVisible(false);
                                dcobj.getCabsObject().setVisible(true);

                                // detailsobj.setVisible(true);
                                break;
                        }
                        if (flag == 1)
                                break;

                }
        }

        public void run() {
                check();
        }

        // public static Details getInstanceOfDetails(Booking obj) {
        // if (instance == null)
        // instance = new Details(obj);
        // return instance;

        // }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                jLabel9 = new javax.swing.JLabel();
                jLabel10 = new javax.swing.JLabel();
                jLabel11 = new javax.swing.JLabel();
                jLabel12 = new javax.swing.JLabel();
                jLabel13 = new javax.swing.JLabel();
                jLabel14 = new javax.swing.JLabel();
                jLabel15 = new javax.swing.JLabel();
                jLabel15.setText(this.dcobj.getBookingObject().getPickupLocation());
                jLabel15.setVisible(true);
                jLabel16 = new javax.swing.JLabel();
                jLabel17 = new javax.swing.JLabel();
                jLabel17.setText(this.dcobj.getBookingObject().getDropLocation());
                jLabel17.setVisible(true);
                jLabel18 = new javax.swing.JLabel();
                jLabel17.setVisible(true);
                jButton1 = new javax.swing.JButton();
                jLabel19 = new javax.swing.JLabel();
                jLabel20 = new javax.swing.JLabel();
                jLabel21 = new javax.swing.JLabel();
                jLabel22 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(204, 255, 255));

                jPanel2.setBackground(new java.awt.Color(153, 0, 51));

                jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText(this.dcobj.getCustomerObject().getName());

                jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                jLabel2.setText("CabX");

                jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(255, 255, 255));
                jLabel3.setText("Profile");
                jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabel3MouseClicked(evt);
                        }
                });

                jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(255, 255, 255));
                jLabel4.setText("Logout");
                jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabel4MouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(jPanel2Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addComponent(jLabel1)
                                                .addGap(278, 278, 278).addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                288, Short.MAX_VALUE)
                                                .addComponent(jLabel3).addGap(56, 56, 56).addComponent(jLabel4)
                                                .addGap(19, 19, 19)));
                jPanel2Layout.setVerticalGroup(jPanel2Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
                                                .createSequentialGroup().addContainerGap(76, Short.MAX_VALUE)
                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel1).addComponent(jLabel2)
                                                                .addComponent(jLabel3).addComponent(jLabel4))
                                                .addContainerGap()));

                jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(153, 0, 0));
                jLabel5.setText("Name of Driver :-");

                jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel6.setForeground(new java.awt.Color(153, 0, 51));
                jLabel6.setText("Name of Vehicle :-");

                jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel7.setForeground(new java.awt.Color(153, 0, 0));
                jLabel7.setText("Pick up location :-");

                jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel8.setForeground(new java.awt.Color(153, 0, 0));
                jLabel8.setText("Vehicle No. :-");

                jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel9.setForeground(new java.awt.Color(153, 0, 0));
                jLabel9.setText("Total Fare :-");

                jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel10.setForeground(new java.awt.Color(153, 0, 0));
                jLabel10.setText("Drop location :-");

                jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel11.setForeground(new java.awt.Color(153, 0, 0));

                jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel12.setForeground(new java.awt.Color(153, 0, 0));
                jLabel12.setText(dcobj.getBookingObject().getDriverName());

                jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel13.setForeground(new java.awt.Color(153, 0, 0));

                jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel14.setForeground(new java.awt.Color(153, 0, 0));
                jLabel14.setText(dcobj.getBookingObject().getVehicleName());

                jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel15.setForeground(new java.awt.Color(153, 0, 0));
                // jLabel15.setText();

                jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel16.setForeground(new java.awt.Color(153, 0, 0));
                jLabel16.setText(this.dcobj.getBookingObject().getVehicleNumber());

                jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel17.setForeground(new java.awt.Color(153, 0, 0));
                // jLabel17.setText("EnterDroploc");

                jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel18.setForeground(new java.awt.Color(153, 0, 0));
                jLabel18.setText(String.valueOf(this.dcobj.getBookingObject().getFare()));

                jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jButton1.setForeground(new java.awt.Color(153, 0, 51));
                jButton1.setText("Cancel Booking");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                jLabel19.setForeground(new java.awt.Color(153, 0, 0));
                jLabel19.setText("Driver mobile number :");

                jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                jLabel20.setForeground(new java.awt.Color(153, 0, 0));
                jLabel20.setText(this.dcobj.getBookingObject().getDriverPhoneNumber());

                jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                jLabel21.setForeground(new java.awt.Color(153, 0, 0));
                jLabel21.setText("Booking ID :");

                jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                jLabel22.setForeground(new java.awt.Color(153, 0, 0));
                jLabel22.setText(String.valueOf(this.dcobj.getBookingObject().getBookingID()));

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup().addGap(62, 62, 62)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGroup(jPanel1Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(jLabel9)
                                                                                                                .addGap(64, 64, 64)
                                                                                                                .addComponent(jLabel18,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                166,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addComponent(jLabel7)
                                                                                                                                .addComponent(jLabel10)
                                                                                                                                .addComponent(jLabel8))
                                                                                                                .addGap(35, 35, 35)
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                false)
                                                                                                                                .addComponent(jLabel13)
                                                                                                                                .addComponent(jLabel17,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addComponent(jLabel15,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                187,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addComponent(jLabel16,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                175,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                                .addGap(0, 506, Short.MAX_VALUE))
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGroup(jPanel1Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(jLabel5)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(jLabel6)
                                                                                                                .addGap(31, 31, 31)
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addComponent(jLabel11)
                                                                                                                                .addComponent(jLabel14,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                175,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addComponent(jLabel12,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                200,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                                .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(jLabel19,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                232,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(jLabel21,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                143,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(jLabel22,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                143,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(jLabel20,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                194,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(27, 27, 27))))
                                .addGroup(jPanel1Layout.createSequentialGroup().addGap(401, 401, 401)
                                                .addComponent(jButton1).addGap(0, 0, Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(34, 34, 34)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel5).addComponent(jLabel12)
                                                                .addComponent(jLabel19).addComponent(jLabel20))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel11).addGap(27, 27, 27)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel6).addComponent(jLabel14)
                                                                .addComponent(jLabel21).addComponent(jLabel22))
                                                .addGap(32, 32, 32)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel8).addComponent(jLabel16))
                                                .addGap(38, 38, 38)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel7).addComponent(jLabel15,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                29,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(13, 13, 13).addComponent(jLabel13).addGap(25, 25, 25)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel10).addComponent(jLabel17,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                29,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42,
                                                                Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel9,
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(jLabel18,
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                29,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(29, 29, 29).addComponent(jButton1).addGap(28, 28, 28)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 22, Short.MAX_VALUE)));
                layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                layout.createSequentialGroup().addContainerGap()
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addContainerGap()));

                pack();
        }// </editor-fold>

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

                this.setVisible(false);
                try {
                        flag = 1;
                        BookingManager.getInstanceOfBookingManager()
                                        .removeBooking(dcobj.getBookingObject().getBookingID());
                        dcobj.getSearchCabObject().setVisible(true);

                } catch (Exception e) {
                        // BookingManager.getInstanceOfBookingManager()
                        // .removeBooking(ddobj.getBookingObject().getBookingID());
                        // ddobj.getDriverHomePageObject().setVisible(true);
                        // TODO: handle exception
                }
                // SearchCab.instance.setVisible(true);
                // TODO add your handling code here:
        }

        private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {
                // TODO add your handling code here:
                this.setVisible(false);
                this.dcobj.getProfileObject().setVisible(true);
        }

        private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {
                // TODO add your handling code here:
                this.setVisible(false);
                this.dcobj.getLoginObject().setVisible(true);
        }

        /**
         * @param args the command line arguments
         */

        // Variables declaration - do not modify
        private javax.swing.JLabel jLabel1;
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JLabel jLabel14;
        private javax.swing.JLabel jLabel15;
        private javax.swing.JLabel jLabel16;
        private javax.swing.JLabel jLabel17;
        private javax.swing.JLabel jLabel18;
        private javax.swing.JLabel jLabel19;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel20;
        private javax.swing.JLabel jLabel21;
        private javax.swing.JLabel jLabel22;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        // End of variables declaration
}
