import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AMIR KHAN
 */
public class DriverHomePage extends javax.swing.JFrame {

        /**
         * Creates new form DriverHomePage
         */
        public DisplayDriver ddobj;

        public DriverHomePage(DisplayDriver ddobj) {
                this.ddobj = ddobj;

                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jLabel3 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jPanel3 = new javax.swing.JPanel();
                jLabel4 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel2.setBackground(new java.awt.Color(153, 0, 102));

                jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(255, 255, 255));
                jLabel3.setText("Profile");
                jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabel3MouseClicked(evt);
                        }
                });

                jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(255, 255, 255));
                jLabel5.setText("Logout");
                jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabel5MouseClicked(evt);
                        }
                });

                jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText("CABX");

                jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                jLabel2.setText(ddobj.getDriverObject().getName());

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(jPanel2Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(183, 183, 183)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(42, 42, 42)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap()));
                jPanel2Layout.setVerticalGroup(jPanel2Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
                                                .createSequentialGroup().addContainerGap(76, Short.MAX_VALUE)
                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel1).addComponent(jLabel2)
                                                                .addComponent(jLabel3).addComponent(jLabel5))
                                                .addContainerGap()));

                jPanel3.setBackground(new java.awt.Color(255, 255, 255));

                jLabel4.setBackground(new java.awt.Color(153, 0, 51));
                jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(153, 0, 102));
                jLabel4.setLabelFor(jLabel4);
                jLabel4.setText("Accept");
                jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED,
                                new java.awt.Color(204, 0, 102), new java.awt.Color(204, 0, 51),
                                new java.awt.Color(204, 0, 51), new java.awt.Color(153, 0, 51)));
                jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabel4MouseClicked(evt);
                        }
                });

                jLabel6.setBackground(new java.awt.Color(153, 0, 51));
                jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel6.setForeground(new java.awt.Color(153, 0, 102));
                jLabel6.setText("Rent");
                jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder(
                                javax.swing.BorderFactory.createTitledBorder(null, "",
                                                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                                                javax.swing.border.TitledBorder.ABOVE_BOTTOM),
                                "", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.TOP));
                jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabel6MouseClicked(evt);
                        }
                });

                jLabel7.setBackground(new java.awt.Color(153, 0, 51));
                jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel7.setForeground(new java.awt.Color(153, 0, 102));
                jLabel7.setText("Search");
                jLabel7.setBorder(javax.swing.BorderFactory.createTitledBorder(
                                javax.swing.BorderFactory.createTitledBorder(null, "",
                                                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                                                javax.swing.border.TitledBorder.ABOVE_BOTTOM),
                                "", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.TOP));
                jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabel7MouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(jPanel3Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup().addGap(108, 108, 108)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                204, Short.MAX_VALUE)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 127,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(179, 179, 179)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 127,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(124, 124, 124)));
                jPanel3Layout.setVerticalGroup(jPanel3Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup().addGap(134, 134, 134)
                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                57,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel6,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                57,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel7,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                57,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(214, Short.MAX_VALUE)));

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                jPanel1Layout.setVerticalGroup(jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }// </editor-fold>

        private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {
                this.setVisible(false);
                // Profile.getProfileObject(0, ddobj).setVisible(true);
                ddobj.getProfileObject().setVisible(true);
                // TODO add your handling code here:

        }

        private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {
                this.setVisible(false);
                ddobj.getRentVehicleObject().setVisible(true);
                // TODO add your handling code here:
        }

        private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {
                // SearchVehicle searchvehobj = SearchVehicle.getIntSearchVehicle(dobj);

                this.jLabel7.setForeground(new java.awt.Color(0, 0, 10));
                if (!this.ddobj.getDriverObject().getVehiclename().equals("null")) {
                        JOptionPane.showMessageDialog(this, "You already own vehicle");
                } else {
                        ddobj.getSearchVehicleObject().setVisible(true);
                        this.setVisible(false);
                }
                // searchvehobj.setVisible(true);
        }

        private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {
                this.jLabel5.setForeground(new java.awt.Color(0, 0, 10));
                this.setVisible(false);
                // loginobj.setVisible(true);
                ddobj.getLoginObject().setVisible(true);
                // AcceptBooking.instance = null;
                // DriverHomePage.instance = null;
                // TODO add your handling code here:
        }

        private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {
                // TODO add your handling code here:
                this.jLabel4.setForeground(new java.awt.Color(0, 0, 10));
                if (this.ddobj.getDriverObject().getVehiclename().equals("null")) {
                        JOptionPane.showMessageDialog(this, "You don't own any vehicle please take rent");
                } else {
                        // AcceptBooking acceptobj = AcceptBooking.getInstanceOfAcceptBooking(dobj);
                        this.setVisible(false);
                        ddobj.getAcceptBookingObject().setVisible(true);
                        // acceptobj.setVisible(true);
                }

        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel. For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */

        }

        // Variables declaration - do not modify
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        // End of variables declaration
}
