/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.JOptionPane;

/**
 *
 * @author AMIR KHAN
 */
public class RegisterUI extends javax.swing.JFrame {

        /**
         * Creates new form RegisterUI
         */
        public AccountManager mgr;
        public static RegisterUI instance;

        public RegisterUI() {
                mgr = AccountManager.getInstance();
                initComponents();
        }

        public static RegisterUI getInstanceOfRegisterUI() {
                if (instance == null)
                        instance = new RegisterUI();
                return instance;
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                jPopupMenu1 = new javax.swing.JPopupMenu();
                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                jPanel4 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                jTextField1 = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                jPasswordField1 = new javax.swing.JPasswordField();
                cust = new javax.swing.JRadioButton();
                driv = new javax.swing.JRadioButton();
                jButton1 = new javax.swing.JButton();
                jLabel5 = new javax.swing.JLabel();
                jTextField2 = new javax.swing.JTextField();
                jLabel6 = new javax.swing.JLabel();
                jPasswordField2 = new javax.swing.JPasswordField();
                jLabel4 = new javax.swing.JLabel();
                jTextField3 = new javax.swing.JTextField();
                jLabel7 = new javax.swing.JLabel();
                jTextField4 = new javax.swing.JTextField();
                jLabel8 = new javax.swing.JLabel();
                jTextField5 = new javax.swing.JTextField();
                jPanel3 = new javax.swing.JPanel();
                cust1 = new javax.swing.JRadioButton();
                jLabel9 = new javax.swing.JLabel();
                jLabel10 = new javax.swing.JLabel();
                jTextField6 = new javax.swing.JTextField();
                jTextField7 = new javax.swing.JTextField();
                jLabel11 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(153, 0, 51));

                jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText("CABX");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                .createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(441, 441, 441)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap(54, Short.MAX_VALUE)
                                                                .addComponent(jLabel1).addContainerGap()));

                jPanel2.setBackground(new java.awt.Color(255, 255, 255));

                jPanel4.setBackground(new java.awt.Color(204, 0, 102));

                jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                jLabel2.setText("Email :");

                jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

                jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(255, 255, 255));
                jLabel3.setText("Password :");

                jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

                cust.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                cust.setForeground(java.awt.Color.red);
                cust.setText("Customer");
                cust.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                custActionPerformed(evt);
                        }
                });

                driv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                // driv.setForeground(new java.awt.Color(255, 255, 255));
                driv.setText("Driver");
                driv.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                drivActionPerformed(evt);
                        }
                });

                jButton1.setBackground(new java.awt.Color(204, 0, 102));
                jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jButton1.setForeground(new java.awt.Color(255, 255, 255));
                jButton1.setText("Submit");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(255, 255, 255));
                jLabel5.setText("Name :");

                jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                jTextField2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextField2ActionPerformed(evt);
                        }
                });

                jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                jLabel6.setForeground(new java.awt.Color(255, 255, 255));
                jLabel6.setText("Confirm Password :");

                jPasswordField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

                jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(255, 255, 255));
                jLabel4.setText("Mobile number :");

                jTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

                jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                jLabel7.setForeground(new java.awt.Color(255, 255, 255));
                jLabel7.setText("Age :");

                jTextField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

                jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                jLabel8.setForeground(new java.awt.Color(255, 255, 255));
                jLabel8.setText("Location :");

                jTextField5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

                jPanel3.setBackground(new java.awt.Color(204, 0, 102));
                this.jPanel3.setVisible(false);

                cust1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                cust1.setForeground(new java.awt.Color(255, 255, 255));
                cust1.setText("Do you have your own vehicle? select if yes");
                cust1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cust1ActionPerformed(evt);
                        }
                });

                jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                jLabel9.setForeground(new java.awt.Color(255, 255, 255));
                jLabel9.setText("Vehicle name :");
                this.jLabel9.setVisible(false);

                jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                jLabel10.setForeground(new java.awt.Color(255, 255, 255));
                jLabel10.setText("Vehicle number :");
                this.jLabel10.setVisible(false);

                jTextField6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                this.jTextField6.setVisible(false);

                jTextField7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                this.jTextField7.setVisible(false);

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(jPanel3Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup().addGap(28, 28, 28)
                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                                .addComponent(jLabel10)
                                                                                .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jTextField7,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                233,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                                .addComponent(jLabel9)
                                                                                .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jTextField6,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                233,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addContainerGap(
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                                .addComponent(cust1,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addGap(98, 98, 98)))));
                jPanel3Layout.setVerticalGroup(jPanel3Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup().addContainerGap().addComponent(cust1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel9).addComponent(jTextField6,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20,
                                                                Short.MAX_VALUE)
                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel10).addComponent(jTextField7,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))));

                jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabel11.setForeground(new java.awt.Color(255, 255, 255));
                jLabel11.setText("Already have an account? Login");
                jLabel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabel11MouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(jPanel4Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup().addGroup(jPanel4Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel4Layout.createSequentialGroup().addGap(29, 29, 29)
                                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel4Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel5)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jTextField2,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                233,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel4Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                false)
                                                                                                .addComponent(driv,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                95,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGroup(jPanel4Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(jLabel2)
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                .addComponent(jTextField1,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                233,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addComponent(cust,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE))
                                                                                .addGroup(jPanel4Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel7)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(jTextField4,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                233,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel4Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel8)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(jTextField5,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                233,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel4Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel4)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jTextField3,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                233,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel4Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel3)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(jPasswordField1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                200,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel4Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel6)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jPasswordField2,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                235,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel4Layout.createSequentialGroup().addGap(159, 159, 159)
                                                                .addComponent(jButton1))
                                                .addGroup(jPanel4Layout.createSequentialGroup().addGap(78, 78, 78)
                                                                .addComponent(jLabel11,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                244,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addContainerGap(47, Short.MAX_VALUE)));
                jPanel4Layout.setVerticalGroup(jPanel4Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup().addGap(18, 18, 18)
                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel5).addComponent(jTextField2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(21, 21, 21)
                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel2).addComponent(jTextField1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel7).addComponent(jTextField4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(24, 24, 24)
                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel8).addComponent(jTextField5,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(28, 28, 28)
                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel4).addComponent(jTextField3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(27, 27, 27)
                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel3).addComponent(jPasswordField1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel6).addComponent(jPasswordField2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18).addComponent(cust)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(driv).addGap(18, 18, 18)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                105, Short.MAX_VALUE)
                                                .addComponent(jLabel11).addGap(18, 18, 18).addComponent(jButton1)
                                                .addGap(26, 26, 26)));

                jScrollPane1.setViewportView(jPanel4);

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(jPanel2Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup().addGap(244, 244, 244)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(229, Short.MAX_VALUE)));
                jPanel2Layout.setVerticalGroup(jPanel2Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap()));

                pack();
        }// </editor-fold>

        private void cust1ActionPerformed(java.awt.event.ActionEvent evt) {
                // TODO add your handling code here:
                if (this.cust1.isSelected()) {
                        this.jLabel10.setVisible(true);
                        this.jLabel9.setVisible(true);
                        this.jTextField6.setVisible(true);
                        this.jTextField7.setVisible(true);
                } else {
                        this.jLabel10.setVisible(false);
                        this.jLabel9.setVisible(false);
                        this.jTextField6.setVisible(false);
                        this.jTextField7.setVisible(false);
                }
        }

        private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
                // TODO add your handling code here:
        }

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
                // TODO add your handling code here:
                int flag = 1;
                if (this.jTextField2.getText().equals("") || this.jTextField1.getText().equals("")
                                || this.jTextField3.getText().equals("") || this.jTextField4.getText().equals("")
                                || this.jTextField5.getText().equals("")
                                || String.valueOf(this.jPasswordField1.getPassword()).equals("")
                                || String.valueOf(this.jPasswordField2.getPassword()).equals("")
                                || !(this.driv.isSelected() || this.cust.isSelected())) {
                        JOptionPane.showMessageDialog(this, "Please fill all the vacant literals");
                        flag = 0;
                } else if (!String.valueOf(this.jPasswordField1.getPassword())
                                .equals(String.valueOf(this.jPasswordField2.getPassword()))) {
                        JOptionPane.showMessageDialog(this, "Password mismatch");
                        flag = 0;
                } else if (this.jTextField3.getText().length() != 10) {
                        JOptionPane.showMessageDialog(this, "Enter valid mobile number");
                        flag = 0;
                }

                if (flag == 1) {
                        try {
                                Long.parseLong(this.jTextField3.getText());
                        } catch (Exception e) {
                                JOptionPane.showMessageDialog(this, "Enter valid mobile number");
                                flag = 0;
                                // TODO: handle exception
                        }
                }
                if (flag == 1) {
                        try {
                                if (Integer.parseInt(this.jTextField4.getText()) > 130) {
                                        JOptionPane.showMessageDialog(this, "Enter valid age");
                                        flag = 0;
                                }

                        } catch (Exception e) {
                                // TODO: handle exception
                                JOptionPane.showMessageDialog(this, "Enter valid age");
                                flag = 0;
                        }
                }
                if (flag == 1) {
                        try {
                                Long.parseLong(this.jTextField5.getText());

                        } catch (Exception e) {
                                // TODO: handle exception
                                JOptionPane.showMessageDialog(this, "Enter valid location");
                                flag = 0;
                        }
                }
                if (flag == 1 && this.driv.isSelected()) {
                        if (this.cust1.isSelected() && (this.jTextField6.getText().equals("")
                                        || this.jTextField7.getText().equals(""))) {
                                JOptionPane.showMessageDialog(this, "Please fill all the vacant literals");
                                flag = 0;
                        }
                }

                if (flag == 1 && this.cust.isSelected()) {
                        try {
                                mgr.displayAccount(this.jTextField1.getText());

                                mgr.searchWithMobileNumber(this.jTextField3.getText());

                        } catch (Exception e) {
                                JOptionPane.showMessageDialog(this,
                                                "This Email or Mobile number is already registered with us");
                                flag = 0;
                                // TODO: handle exception
                        }

                        if (mgr.createAccount(new Customer(this.jTextField2.getText(), this.jTextField1.getText(),
                                        String.valueOf(this.jPasswordField1.getPassword()), this.jTextField4.getText(),
                                        this.jTextField3.getText(), this.jTextField5.getText()))) {
                                JOptionPane.showMessageDialog(this, "Registration Successfull");
                                this.setVisible(false);
                                // LoginUI.getInstanceOfLoginUI().setVisible(true);
                                LoginUI.getInstanceOfLogin().setVisible(true);
                        } else {
                                JOptionPane.showMessageDialog(this, "Please try again");
                        }

                } else if (flag == 1 && this.driv.isSelected()) {
                        try {
                                mgr.displayAccount(this.jTextField1.getText(), 'a');

                                mgr.searchWithMobileNumberD(this.jTextField3.getText());

                        } catch (Exception e) {
                                JOptionPane.showMessageDialog(this,
                                                "This Email or Mobile number is already registered with us");
                                flag = 0;
                                // TODO: handle exception
                        }
                        if (flag == 1 && cust1.isSelected() && mgr.createAccount(new Driver(this.jTextField2.getText(),
                                        this.jTextField1.getText(), String.valueOf(this.jPasswordField1.getPassword()),
                                        this.jTextField4.getText(), this.jTextField3.getText(),
                                        this.jTextField5.getText(), this.jTextField6.getText(),
                                        this.jTextField7.getText()))) {
                                JOptionPane.showMessageDialog(this, "Registration Successfull");
                                this.setVisible(false);
                                LoginUI.getInstanceOfLogin().setVisible(true);
                        } else if (flag == 1 && !this.cust1.isSelected()) {
                                if (mgr.createAccount(new Driver(this.jTextField2.getText(), this.jTextField1.getText(),
                                                String.valueOf(this.jPasswordField1.getPassword()),
                                                this.jTextField4.getText(), this.jTextField3.getText(),
                                                this.jTextField5.getText(), "null", "null"))) {
                                        JOptionPane.showMessageDialog(this, "Registration Successfull");
                                        this.setVisible(false);
                                        LoginUI.getInstanceOfLogin().setVisible(true);
                                }
                        } else {
                                JOptionPane.showMessageDialog(this, "Please try again");
                        }
                }
                // System.out.print(this.jTextField3.getText().length()<10);

                // System.out.println(String.valueOf(this.jPasswordField1.getPassword())
                // .equals(String.valueOf(this.jPasswordField2.getPassword())));
        }

        private void drivActionPerformed(java.awt.event.ActionEvent evt) {
                // TODO add your handling code here:
                if (this.driv.isSelected())
                        this.cust.setSelected(false);
                this.jPanel3.setVisible(true);
        }

        private void custActionPerformed(java.awt.event.ActionEvent evt) {
                if (this.cust.isSelected())
                        this.driv.setSelected(false);
                this.jPanel3.setVisible(false);
                // TODO add your handling code here:
        }

        private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {

                this.setVisible(false);
                LoginUI.getInstanceOfLogin().setVisible(true);
                // TODO add your handling code here:
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel. For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */

                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new RegisterUI().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify
        private javax.swing.JRadioButton cust;
        private javax.swing.JRadioButton cust1;
        private javax.swing.JRadioButton driv;
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPasswordField jPasswordField1;
        private javax.swing.JPasswordField jPasswordField2;
        private javax.swing.JPopupMenu jPopupMenu1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTextField jTextField1;
        private javax.swing.JTextField jTextField2;
        private javax.swing.JTextField jTextField3;
        private javax.swing.JTextField jTextField4;
        private javax.swing.JTextField jTextField5;
        private javax.swing.JTextField jTextField6;
        private javax.swing.JTextField jTextField7;
        // End of variables declaration
}
