import java.io.IOException;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

// import com.mycompany.searchcab.Details;
/**
 *
 * @author AMIR KHAN
 */

public class SearchCab extends javax.swing.JFrame {

        /**
         * Creates new form NewJFrame
         */
        public String pickup;
        public String drop;
        public DisplayCustomer dcobj;

        public SearchCab(DisplayCustomer dcobj) {
                this.dcobj = dcobj;

                initComponents();

        }

        void searchBooking() {

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jTextField1 = new javax.swing.JTextField();
                jTextField2 = new javax.swing.JTextField();
                jButton2 = new javax.swing.JButton();
                jButton1 = new javax.swing.JButton();
                jLabel6 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setLocation(new java.awt.Point(150, 65));
                setMaximumSize(new java.awt.Dimension(450, 300));
                setPreferredSize(new java.awt.Dimension(1200, 750));

                jPanel2.setBackground(new java.awt.Color(153, 0, 0));

                jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText(dcobj.getCustomerObject().getName());

                jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                jLabel2.setText("CabX");

                jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(255, 255, 255));
                jLabel3.setText("Profile");
                jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabel3MouseClicked(evt);
                        }
                });

                jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(255, 255, 255));
                jLabel4.setText("Logout");
                jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabel4MouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(jPanel2Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel2).addGap(245, 245, 245).addComponent(jLabel3)
                                                .addGap(83, 83, 83).addComponent(jLabel4).addGap(16, 16, 16)));
                jPanel2Layout.setVerticalGroup(jPanel2Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
                                                .createSequentialGroup().addContainerGap(76, Short.MAX_VALUE)
                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel1).addComponent(jLabel2)
                                                                .addComponent(jLabel3).addComponent(jLabel4))
                                                .addContainerGap()));

                jLabel5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
                jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel5.setText("Request a ride now");

                jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                jTextField1.setText("Enter pickup location...");

                jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                jTextField2.setText("Enter drop location...");
                jTextField2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextField2ActionPerformed(evt);
                        }
                });

                jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jButton2.setForeground(new java.awt.Color(153, 0, 102));
                jButton2.setText("My bookings");
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton2ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                .createSequentialGroup().addContainerGap(449, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jTextField2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                467,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jTextField1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                467,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(jLabel5)
                                                                                .addGap(71, 71, 71)
                                                                                .addComponent(jButton2)))
                                                .addGap(80, 80, 80)));
                jPanel1Layout.setVerticalGroup(jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jPanel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(75, 75, 75).addComponent(jLabel5))
                                                .addGroup(jPanel1Layout.createSequentialGroup().addGap(171, 171, 171)
                                                                .addComponent(jButton2)))
                                                .addGap(28, 28, 28)
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 53,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 66,
                                                                Short.MAX_VALUE)
                                                .addGap(17, 17, 17)));

                jButton1.setText("Submit");
                jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 51), 30, true));
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup().addGap(0, 608, Short.MAX_VALUE)
                                                                .addComponent(jButton1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                137,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(445, 445, 445))
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 383,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(276, 276, 276)));
                layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup().addContainerGap()
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(125, 125, 125)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18).addComponent(jButton1)
                                                .addContainerGap(85, Short.MAX_VALUE)));

                pack();
        }// </editor-fold>

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
                // pickup=this.jTextField1.getText();
                int flag = 1;
                pickup = this.jTextField1.getText();
                drop = this.jTextField2.getText();
                if (pickup.equals("") && drop.equals("")) {
                        JOptionPane.showMessageDialog(this, "Enter pickup and drop location");
                        flag = 0;
                } else if (pickup.equals("")) {
                        JOptionPane.showMessageDialog(this, "Enter pickup location");
                        flag = 0;
                } else if (drop.equals("")) {
                        JOptionPane.showMessageDialog(this, "Enter drop location");
                        flag = 0;
                } else if (flag == 1) {
                        try {
                                Long.parseLong(this.jTextField1.getText());
                                Long.parseLong(this.jTextField2.getText());
                        } catch (Exception e) {
                                // TODO: handle exception
                                JOptionPane.showMessageDialog(this, "Enter correct details");
                                flag = 0;

                        }
                }
                if (flag == 1) {
                        try {
                                Booking bkg = BookingManager.getInstanceOfBookingManager()
                                                .getBookingObjectWithMobileNumber(
                                                                dcobj.getCustomerObject().getPhoneNumber());
                                System.out.print(bkg.getCustomerName());
                                bkg.getBookingID();
                                JOptionPane.showMessageDialog(this, "Complete the previous booking or cancel it");
                                flag = 0;

                        } catch (Exception e) {
                                // TODO: handle exception
                        }
                }

                if (flag == 1) {
                        Booking b1 = new Booking(dcobj.getCustomerObject().getName(),
                                        dcobj.getCustomerObject().getPhoneNumber(), pickup, drop);

                        BookingManager bmgr = BookingManager.getInstanceOfBookingManager();
                        b1.setBookingID(bmgr.getMaxBookingID() + 1);

                        bmgr.addBooking(b1);
                        // bmgr.reWriteInBookingFile(b1);
                        this.dcobj.setBookingObject(b1);
                        // this.jLabel6.setText("Details will be updated as soon as driver accepts
                        // booking");
                        // Cabs cabsobj = Cabs.getInstanceOfCabs(dcobj, b1);
                        this.setVisible(false);
                        dcobj.getCabsObject().setVisible(true);
                        // cabsobj.setVisible(true);

                }
        }

        private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
                // TODO add your handling code here:
        }

        private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {
                // Profile custprof = Profile.getProfileObject(1, dcobj);
                this.setVisible(false);
                // custprof.setVisible(true);
                dcobj.getProfileObject().setVisible(true);

                // TODO add your handling code here:
        }

        private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {
                this.setVisible(false);
                // loginobj.setVisible(true);
                dcobj.getLoginObject().setVisible(true);
                // TODO add your handling code here:
        }

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
                // TODO add your handling code here:
                // if (dcobj.getDetailsObject().flag == 1) {
                // if (dcobj.getCabsObject().temp_flag == 0) {
                // this.setVisible(false);
                // // Cabs.getInstanceOfCabs(cobj, this.bkg).setVisible(true);
                // dcobj.getCabsObject().setVisible(true);
                // } else
                // JOptionPane.showMessageDialog(this, "Currently there is no booking
                // available");
                // } else {
                // this.setVisible(false);
                // // Details.instance.setVisible(true);
                // dcobj.getDetailsObject().setVisible(true);
                // }
                BookingManager.getInstanceOfBookingManager().isCalledOnce();

                Booking bkg = BookingManager.getInstanceOfBookingManager()
                                .getBookingObjectWithMobileNumber(dcobj.getCustomerObject().getPhoneNumber());
                // System.out.print(bkg.getCustomerName());
                try {
                        if (bkg.getStatus() == 0) {
                                this.setVisible(false);
                                dcobj.setBookingObject(bkg);
                                dcobj.getCabsObject().setVisible(true);
                        } else {
                                this.setVisible(false);
                                dcobj.setBookingObject(bkg);
                                dcobj.getDetailsObject().setVisible(true);
                        }
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Currently there is no booking available");
                        // TODO: handle exception

                }

        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) throws IOException {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel. For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                // new SearchCab().setVisible(true);
        }

        // Variables declaration - do not modify
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JTextField jTextField1;
        private javax.swing.JTextField jTextField2;
        // End of variables declaration
}
