
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author AMIR KHAN
 */
public class SearchVehicle extends javax.swing.JFrame {

        public DefaultListModel<String> model = new DefaultListModel<>();
        public DisplayDriver ddobj;
        /**
         * Creates new form SearchVehicle
         */

        public static SearchVehicle instance;

        public SearchVehicle(DisplayDriver ddobj) {
                this.ddobj = ddobj;
                addToModel();
                initComponents();
        }

        public void addToModel() {
                VehicleManager vm = VehicleManager.getInstanceOfVehicleManager();
                for (int i = 0; i < vm.car.size(); i++) {
                        model.add(model.size(), vm.car.get(i).getName() + "        " + vm.car.get(i).getLocation()
                                        + "        " + vm.car.get(i).getCarID());
                }
        }

        public void viewDetails(int carID) {
                VehicleManager vm = VehicleManager.getInstanceOfVehicleManager();
                Car c = vm.getObjectWithID(carID);
                // new VehicleDetails(dobj, c).setVisible(true);
                this.setVisible(false);
                this.ddobj.setCarObject(c);
                // VehicleDetails.getInstanceOfVehicleDetails(dobj, c).setVisible(true);

                // ddobj.getDriverObject().setVehiclename(c.getName());
                // ddobj.getDriverObject().setVehiclenumber(c.getNumber());
                c.setLicenceNumber("wbx2ou");
                // VehicleManager.getInstanceOfVehicleManager().removeVehicle(c.getCarID());
                // AccountManager.getInstance().reWriteAccountDetailsDriver(ddobj.getDriverObject());
                // VehicleManager.getInstanceOfVehicleManager().addRent(ddobj.getRentalObject());
                // this.ddobj.getDriverHomePageObject().setVisible(true);
                this.ddobj.getVehicleDetailsObject().setVisible(true);

                // dispose();
                // new VehicleDetails(dobj, c);

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                jLabel4 = new javax.swing.JLabel();
                jPanel4 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jPanel1 = new javax.swing.JPanel();
                jLabel6 = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                jScrollPane3 = new javax.swing.JScrollPane();
                jList2 = new javax.swing.JList<>();

                jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(255, 255, 255));
                jLabel4.setText("Profile");

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel4.setBackground(new java.awt.Color(153, 0, 51));

                jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText(ddobj.getDriverObject().getName());

                jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                jLabel2.setText("Profile");
                jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabel2MouseClicked(evt);
                        }
                });

                jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(255, 255, 255));
                jLabel3.setText("Search");

                jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(255, 255, 255));
                jLabel5.setText("Logout");
                jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabel5MouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(jPanel4Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup().addGap(18, 18, 18)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                226, Short.MAX_VALUE)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(117, 117, 117)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(47, 47, 47)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 114,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(31, 31, 31)));
                jPanel4Layout.setVerticalGroup(jPanel4Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup().addContainerGap(88, Short.MAX_VALUE)
                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel1).addComponent(jLabel2)
                                                                .addComponent(jLabel3).addComponent(jLabel5))
                                                .addContainerGap()));

                jPanel1.setBackground(new java.awt.Color(255, 255, 255));

                jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel6.setForeground(new java.awt.Color(153, 0, 51));
                jLabel6.setText("List Of Vehicles");
                jList2.setModel(model);
                MouseListener mouseListener = new MouseAdapter() {
                        public void mouseClicked(MouseEvent mouseEvent) {
                                JList<String> theList = (JList) mouseEvent.getSource();
                                if (mouseEvent.getClickCount() == 2) {
                                        int index = theList.locationToIndex(mouseEvent.getPoint());
                                        if (index >= 0) {
                                                Object o = theList.getModel().getElementAt(index);
                                                String[] strarr = o.toString().split("        ");
                                                viewDetails(Integer.parseInt(strarr[2]));
                                                System.out.println("Double-clicked on: " + o.toString());
                                        }
                                }
                        }
                };
                jList2.addMouseListener(mouseListener);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup().addGap(367, 367, 367)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 202,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
                                                                .addComponent(jLabel6)
                                                                .addContainerGap(132, Short.MAX_VALUE)));

                jList2.setBackground(new java.awt.Color(153, 0, 51));
                jList2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                jList2.setForeground(new java.awt.Color(255, 255, 255));
                jScrollPane3.setViewportView(jList2);

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane3));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 230,
                                                                Short.MAX_VALUE));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));

                pack();
        }// </editor-fold>

        private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {
                this.setVisible(false);
                // Profile.getProfileObject(0, ddobj).setVisible(true);
                ddobj.getProfileObject().setVisible(true);
                // TODO add your handling code here:
        }

        private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {
                this.setVisible(false);
                // LoginUI.getInstanceOfLoginUI().setVisible(true);
                ddobj.getLoginObject().setVisible(true);

                // TODO add your handling code here:
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel. For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */

        }

        // Variables declaration - do not modify
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JList<String> jList2;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JScrollPane jScrollPane3;
        // End of variables declaration
}
