/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AMIR KHAN
 */

import java.time.format.DateTimeFormatter;

import javax.swing.JOptionPane;

import java.time.LocalDateTime;

public class VehicleDetails extends javax.swing.JFrame {
        /**
         * Creates new form RentVehicle
         */
        AccountManager am = AccountManager.getInstance();
        VehicleManager vm = VehicleManager.getInstanceOfVehicleManager();
        public DisplayDriver ddobj;

        public VehicleDetails(DisplayDriver ddobj) {
                this.ddobj = ddobj;
                initComponents();
        }

        public void UpdateDetails() {
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
                LocalDateTime now = LocalDateTime.now();
                String[] starr = dtf.format(now).split(" ");
                String[] arr2 = starr[0].split("/");
                int dur = Integer.parseInt(this.jTextField5.getText());
                int day = Integer.parseInt(arr2[2]);
                int month = Integer.parseInt(arr2[1]);
                int year = Integer.parseInt(arr2[0]);
                if (day + dur > 31) {
                        if (month == 12) {
                                year += 1;
                                month = 1;
                        } else
                                month += 1;
                        day -= 31 - dur;
                }
                Rental r = new Rental(ddobj.getCarObject().getOwner(), ddobj.getCarObject().getNumber(),
                                dtf.format(now), year + "/" + month + "/" + day, dur, "10000",
                                ddobj.getDriverObject().getLocation(), ddobj.getDriverObject().getName(),
                                ddobj.getDriverObject().getPhoneNumber(), ddobj.getCarObject().getOwnerPhoneNumber(),
                                67);
                r.setEndDate(year + "/" + month + "/" + day);
                vm.addRent(r);
                ddobj.getDriverObject().setVehiclename(ddobj.getCarObject().getName());
                ddobj.getDriverObject().setVehiclenumber(ddobj.getCarObject().getNumber());
                VehicleManager.getInstanceOfVehicleManager().removeVehicle(ddobj.getCarObject().getCarID());
                AccountManager.getInstance().reWriteAccountDetailsDriver(ddobj.getDriverObject());

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                jPanel2 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                jPanel3 = new javax.swing.JPanel();
                jLabel6 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                jLabel9 = new javax.swing.JLabel();
                jLabel10 = new javax.swing.JLabel();
                jLabel11 = new javax.swing.JLabel();
                jTextField5 = new javax.swing.JTextField();
                jButton1 = new javax.swing.JButton();
                jLabel12 = new javax.swing.JLabel();
                jLabel13 = new javax.swing.JLabel();
                jLabel14 = new javax.swing.JLabel();
                jLabel15 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel2.setBackground(new java.awt.Color(153, 0, 51));

                jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText("Rent");

                jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                jLabel2.setText(ddobj.getDriverObject().getName());

                jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(255, 255, 255));
                jLabel3.setText("Profile");
                jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabel3MouseClicked(evt);
                        }
                });

                jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(255, 255, 255));
                jLabel5.setText("Logout");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(jPanel2Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(227, 227, 227)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(92, 92, 92)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 160,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap()));
                jPanel2Layout.setVerticalGroup(jPanel2Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
                                                .createSequentialGroup().addContainerGap(76, Short.MAX_VALUE)
                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel1).addComponent(jLabel2)
                                                                .addComponent(jLabel3).addComponent(jLabel5))
                                                .addContainerGap()));

                jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel6.setForeground(new java.awt.Color(153, 0, 51));
                jLabel6.setText("Name of Vehicle : ");

                jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel7.setForeground(new java.awt.Color(153, 0, 51));
                jLabel7.setText("Vehicle Details");

                jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel8.setForeground(new java.awt.Color(153, 0, 51));
                jLabel8.setText("Model  :");

                jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel9.setForeground(new java.awt.Color(153, 0, 51));
                jLabel9.setText("Vehicle No.  :");

                jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel10.setForeground(new java.awt.Color(153, 0, 51));
                jLabel10.setText("Owner name :");

                jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel11.setForeground(new java.awt.Color(153, 0, 51));
                jLabel11.setText("Enter duration of rent :");

                jTextField5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jTextField5.setForeground(new java.awt.Color(153, 0, 51));
                jTextField5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextField5ActionPerformed(evt);
                        }
                });

                jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jButton1.setForeground(new java.awt.Color(153, 0, 51));
                jButton1.setText("Confirm ");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel12.setForeground(new java.awt.Color(153, 0, 51));
                jLabel12.setText(ddobj.getCarObject().getName());

                jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel13.setForeground(new java.awt.Color(153, 0, 51));
                jLabel13.setText(ddobj.getCarObject().getModel());

                jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel14.setForeground(new java.awt.Color(153, 0, 51));
                jLabel14.setText(ddobj.getCarObject().getNumber());

                jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel15.setForeground(new java.awt.Color(153, 0, 51));
                jLabel15.setText(ddobj.getCarObject().getOwner());

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(jPanel3Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup().addGroup(jPanel3Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup().addGap(338, 338, 338)
                                                                .addComponent(jLabel7,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                190,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel3Layout.createSequentialGroup().addGap(18, 18, 18)
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel3Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                .addComponent(jButton1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                105,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGroup(jPanel3Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGroup(jPanel3Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addComponent(jLabel8)
                                                                                                                                .addComponent(jLabel6)
                                                                                                                                .addComponent(jLabel9)
                                                                                                                                .addComponent(jLabel10))
                                                                                                                .addGap(20, 20, 20)
                                                                                                                .addGroup(jPanel3Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addComponent(jLabel15)
                                                                                                                                .addComponent(jLabel14)
                                                                                                                                .addComponent(jLabel12)
                                                                                                                                .addComponent(jLabel13))
                                                                                                                .addGap(66, 66, 66)))
                                                                                .addGroup(jPanel3Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel11)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(jTextField5,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                285,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                .addContainerGap(353, Short.MAX_VALUE)));
                jPanel3Layout.setVerticalGroup(jPanel3Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup().addContainerGap().addComponent(jLabel7)
                                                .addGap(46, 46, 46)
                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel6).addComponent(jLabel12))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel8).addComponent(jLabel13))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel9).addComponent(jLabel14))
                                                .addGap(29, 29, 29)
                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel10).addComponent(jLabel15))
                                                .addGap(29, 29, 29)
                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel11).addComponent(jTextField5,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59,
                                                                Short.MAX_VALUE)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(56, 56, 56)));

                jScrollPane1.setViewportView(jPanel3);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0,
                                                Short.MAX_VALUE));
                layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)));

                pack();
        }// </editor-fold>

        private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {
                // TODO add your handling code here:
        }

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDetails();
                JOptionPane.showMessageDialog(this, "Successfully taken vehicle on rent");
                this.setVisible(false);
                // DriverHomePage.getInstanceOfDriverHomePage(dobj).setVisible(true);
                ddobj.getDriverHomePageObject().setVisible(true);
                // TODO add your handling code here:
        }

        private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {
                // TODO add your handling code here:

        }

        public static void main(String[] args) {
                new VehicleDetails(new DisplayDriver(new Driver("d", "d", "d", "d", "d", "d", "d", "d")))
                                .setVisible(true);
                ;
        }

        /**
         * @param args the command line arguments
         */
        // public static void main(String args[]) {
        // /* Set the Nimbus look and feel */
        // //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        // /* If Nimbus (introduced in Java SE 6) is not available, stay with the
        // default look and feel.
        // * For details see
        // http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        // */
        // try {
        // for (javax.swing.UIManager.LookAndFeelInfo info :
        // javax.swing.UIManager.getInstalledLookAndFeels()) {
        // if ("Nimbus".equals(info.getName())) {
        // javax.swing.UIManager.setLookAndFeel(info.getClassName());
        // break;
        // }
        // }
        // } catch (ClassNotFoundException ex) {
        // java.util.logging.Logger.getLogger(VehicleDetails.class.getName()).log(java.util.logging.Level.SEVERE,
        // null, ex);
        // } catch (InstantiationException ex) {
        // java.util.logging.Logger.getLogger(VehicleDetails.class.getName()).log(java.util.logging.Level.SEVERE,
        // null, ex);
        // } catch (IllegalAccessException ex) {
        // java.util.logging.Logger.getLogger(VehicleDetails.class.getName()).log(java.util.logging.Level.SEVERE,
        // null, ex);
        // } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        // java.util.logging.Logger.getLogger(VehicleDetails.class.getName()).log(java.util.logging.Level.SEVERE,
        // null, ex);
        // }
        // //</editor-fold>
        // //</editor-fold>

        // /* Create and display the form */
        // java.awt.EventQueue.invokeLater(new Runnable() {
        // public void run() {
        // new VehicleDetails().setVisible(true);
        // }
        // });
        // }

        // Variables declaration - do not modify
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JLabel jLabel14;
        private javax.swing.JLabel jLabel15;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTextField jTextField5;
        // End of variables declaration
}
